### ISSUE TITLE
Sega Genesis box arts

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/no-intro-thumbnails#6]
thegamesdb has some wrong box arts in its set. Here what I found, in the case we move to 512:

```
    modified:   Sega - Mega Drive - Genesis/Named_Boxarts/Advanced Busterhawk Gleylancer (Japan).png
    modified:   Sega - Mega Drive - Genesis/Named_Boxarts/Alisia Dragoon (Europe).png
    modified:   Sega - Mega Drive - Genesis/Named_Boxarts/Alisia Dragoon (Japan).png
	modified:   Sega - Mega Drive - Genesis/Named_Boxarts/Alisia Dragoon (USA).png
	modified:   Sega - Mega Drive - Genesis/Named_Boxarts/Beyond Oasis (USA).png
	modified:   Sega - Mega Drive - Genesis/Named_Boxarts/Story of Thor, The - Hikari o Tsugumono (Japan).png
	modified:   Sega - Mega Drive - Genesis/Named_Boxarts/Dr. Robotnik's Mean Bean Machine (USA).png
	modified:   Sega - Mega Drive - Genesis/Named_Boxarts/Hellfire (Europe).png
	new file:   Sega - Mega Drive - Genesis/Named_Boxarts/Pulseman (Japan).png
	modified:   Sega - Mega Drive - Genesis/Named_Boxarts/Ranger X (Europe).png
    modified:   Sega - Mega Drive - Genesis/Named_Boxarts/Sonic Spinball (Japan).png
	modified:   Sega - Mega Drive - Genesis/Named_Boxarts/Sonic The Hedgehog (Japan, Korea).png
	modified:   Sega - Mega Drive - Genesis/Named_Boxarts/Sonic The Hedgehog 3 (Europe).png
	modified:   Sega - Mega Drive - Genesis/Named_Boxarts/Sonic The Hedgehog 3 (Japan, Korea).png
	modified:   Sega - Mega Drive - Genesis/Named_Boxarts/Sonic The Hedgehog Spinball (Europe).png
	modified:   Sega - Mega Drive - Genesis/Named_Boxarts/Teenage Mutant Hero Turtles - The Hyperstone Heist (Europe).png
```

**Comment by sergiobenrocha2** [comment]
Basically all the Europe & Japan files mirror the USA files.

**Comment by sergiobenrocha2** [comment]
It seems thegamesdb uses "custom/fan art/mockup" covers for some games, like this: http://thegamesdb.net/banners/boxart/original/front/2611-1.jpg

This game released only on Japan as far as I know.

The Cover Project has more accurate covers for each region (but some covers seems more 'flat', probably filters used?). Moby Games has some too.

**Comment by twinaphex** [comment]
Yeah we definitely need to check for accuracy manually, I think a lot of these existing databases that have scrapable covers just pick whatever boxart they can find, whether or not it is real or not.

**Comment by RobLoach** [comment]
> we definitely need to check for accuracy manually

Put together [libretro-thumbnails-check](https://github.com/RobLoach/libretro-thumbnails-check) to help with checking. Still could use some tweaks, but the result is pretty neat: [Sega - Mega Drive - Genesis.txt](https://github.com/RobLoach/libretro-thumbnails-check/blob/master/out/Sega%20-%20Mega%20Drive%20-%20Genesis.txt)

**Comment by lasers** [comment]
The world be changin'. What do we do with digital games?

I'm assuming all this versions were emulated on Gamecube.
```
./Pokemon Party Mini - Ricochet Dribble (Japan) (GameCube).zip
./Pokemon Party Mini - Rocket Start (USA) (GameCube).zip
./Snorlax's Lunch Time (Japan) (GameCube).zip
./Pokemon Party Mini - Baseline Judge (USA) (GameCube).zip
./Pokemon Party Mini - Slowking's Judge (Europe) (GameCube).zip
./Pokemon Pinball Mini (USA) (GameCube Preview).zip
./Snorlax's Lunch Time (Europe) (GameCube).zip
./Pokemon Puzzle Collection (Germany) (GameCube Preview).zip
./Pokemon Puzzle Collection (France) (GameCube Preview).zip
./Pokemon Party Mini - Baseline Judge (Europe) (GameCube).zip
./Pokemon Party Mini - Pikachu's Rocket Start (Europe) (GameCube).zip
./Pokemon Party Mini - Chansey's Dribble (Europe) (GameCube).zip
./Pokemon Party Mini - Ricochet Dribble (USA) (GameCube).zip
./Lunch Time (USA) (GameCube).zip
./Pokemon Party Mini - Baseline Judge (Japan) (GameCube).zip
./Pokemon Puzzle Collection (Japan) (GameCube).zip
./Pokemon Puzzle Collection (USA) (GameCube Preview).zip
```
Should I remove those and keep the boxarts for official versions only?
```
.
./Togepi no Daibouken (Japan) (Preview).zip
./Pokemon Party Mini (Europe).zip
./Pokemon Puzzle Collection (Germany).zip
./Pokemon Race Mini (Japan).zip
./Pichu Bros. Mini (Japan).zip
./Togepi no Daibouken (Japan).zip
./Pokemon Party Mini (USA).zip
./Pokemon Sodateyasan Mini (Japan).zip
./Pichu Bros. Mini - Hoppip's Jump Match (Japan) (Preview).zip
./Pokemon Shock Tetris (Japan).zip
./Pokemon Pinball Mini (USA, Europe).zip
./Pokemon Tetris (Europe) (En,Ja,Fr).zip
./Pokemon Anime Card Daisakusen (Japan).zip
./Pichu Bros. Mini - Skateboard (Japan) (Preview).zip
./Pokemon Zany Cards (Germany).zip
./Pokemon Race Mini (Japan) (Preview).zip
./Pokemon Puzzle Collection Vol. 2 (Japan).zip
./Pokemon Puzzle Collection (France).zip
./Pokemon Pinball Mini (Japan).zip
./Pichu Bros. Mini - Netsukikyuu (Japan) (Preview).zip
./Pokemon Pinball Mini (Japan) (Preview).zip
./Pokemon Puzzle Collection (USA, Europe).zip
./Pokemon Puzzle Collection (Japan).zip
./[BIOS] Nintendo Pokemon Mini (World).zip
./Pokemon Zany Cards (France).zip
./Pokemon Zany Cards (USA, Europe).zip
./Pokemon Party Mini (Japan).zip
```
I don't like it at all. I would rather keep them all. ;__;

**Comment by sergiobenrocha2** [comment]
This is another case. What's the 'box' used in the virtual console?

**Comment by lasers** [comment]
The 'box' used in virtual console looks like this, I guess. http://www.youtube.com/watch?v=pbA3Uqo--PM

**Comment by sergiobenrocha2** [comment]
@RobLoach there are some false positive there, titles with &

Are there any way to it show 'orphans' png ? Sometimes no-intro change the name in a way you think it's missing art (mainly Japanese titles).

**Comment by RobLoach** [comment]
> there are some false positive there, titles with &

[Fixed](https://github.com/RobLoach/libretro-thumbnails-check/commit/951243fa91e999165f0890288c49bd5d85f14a21). Running another update now.

**Comment by RobLoach** [comment]
https://github.com/RobLoach/libretro-thumbnails-check/blob/master/out/Sega%20-%20Mega%20Drive%20-%20Genesis.txt

```
Boxarts  1454/1701  85.48%
Snaps    1635/1701  96.12%
Titles   1633/1701  96.00%
Total    4722/5103  92.53%
```

**Comment by RobLoach** [comment]
https://github.com/RobLoach/libretro-thumbnails-check/blob/master/out/Sega%20-%20Mega%20Drive%20-%20Genesis%20Orphans.txt

**Comment by sergiobenrocha2** [comment]
There are some false positive there, what dat are you using? From libretro-database or these dats in this repo? Btw, why do we still have them? They are all out of date

**Comment by markwkidd** [comment]
@sergiobenrocha2  the MegaDrive/Genesis 'orphans' list got an update 4 days ago. Is it working as expected now? https://github.com/RobLoach/libretro-thumbnails-check/blob/master/out/Sega%20-%20Mega%20Drive%20-%20Genesis%20Orphans.txt

**Comment by RobLoach** [comment]
It's possible that the `[` and `]` brackets are messing up the check.

**Comment by RobLoach** [comment]
The `[` issue is fixed.
